/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 15-Jun-2018 13:43:53 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS mass_balance.analysis_method_type CASCADE
;

/* Create Tables */

CREATE TABLE mass_balance.analysis_method_type
(
	pk smallint NOT NULL,
	short_name varchar(100) NOT NULL,
	description varchar(250) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE mass_balance.analysis_method_type ADD CONSTRAINT pk_analysis_method_type
	PRIMARY KEY (pk)
;

ALTER TABLE mass_balance.analysis_method_type 
  ADD CONSTRAINT uq_analysis_method_type_pk UNIQUE (pk)
;
