/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 15-Jun-2018 14:29:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS mass_balance.elevation_distribution CASCADE;

/* Create Tables */

CREATE TABLE mass_balance.elevation_distribution
(
	pk uuid NOT NULL,
	fk_mass_balance uuid NOT NULL,
	elevation_from smallint NOT NULL,
	elevation_to smallint NOT NULL,
	mass_balance_annual integer NOT NULL,
	mass_balance_winter integer NOT NULL,
	area numeric(9,5) NOT NULL,
	remarks varchar(500) NULL,
	FOREIGN KEY (fk_mass_balance) REFERENCES mass_balance.mass_balance (pk) ON DELETE CASCADE
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE mass_balance.elevation_distribution ADD CONSTRAINT pk_mass_balance_elevation_distribution_definition
	PRIMARY KEY (pk);

ALTER TABLE mass_balance.elevation_distribution 
  ADD CONSTRAINT uq_mass_balance_elevation_distribution_definition_pk UNIQUE (pk);
  
CREATE INDEX "IXFK_elevation_distribution_mass_balance" ON mass_balance.elevation_distribution (fk_mass_balance ASC);

CREATE INDEX "IXFK_elevation_distribution_pk" ON mass_balance.elevation_distribution (pk ASC);
  
/* Create Foreign Key Constraints */

ALTER TABLE mass_balance.elevation_distribution ADD CONSTRAINT fk_mass_balance_elevation_distribution_mass_balance
	FOREIGN KEY (fk_mass_balance) REFERENCES mass_balance.mass_balance (pk) ON DELETE CASCADE ON UPDATE CASCADE;