/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 15-Jun-2018 13:43:26 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS mass_balance.mass_balance_type CASCADE
;

/* Create Tables */

CREATE TABLE mass_balance.mass_balance_type
(
	pk smallint NOT NULL,
	short_name varchar(100) NOT NULL,
	description varchar(250) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE mass_balance.mass_balance_type ADD CONSTRAINT pk_mass_balance_type
	PRIMARY KEY (pk)
;

ALTER TABLE mass_balance.mass_balance_type 
  ADD CONSTRAINT uq_mass_balance_type_pk UNIQUE (pk)
;
