/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 15-Jun-2018 14:12:06 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS mass_balance.mass_balance CASCADE
;

/* Create Tables */

CREATE TABLE mass_balance.mass_balance
(
	pk uuid NOT NULL,
	fk_glacier uuid NOT NULL,
	fk_mass_balance_type smallint NOT NULL,
	fk_embargo_type smallint NOT NULL   DEFAULT 0,
	fk_analysis_method smallint NOT NULL,
	date_from_annual date NOT NULL,
	date_to_annual date NOT NULL,
	date_from_winter date NOT NULL,
	date_to_winter date NOT NULL,
	area numeric(9,5) NOT NULL,
	mass_balance_annual integer NOT NULL,
	mass_balance_winter integer NOT NULL,
	equilibrium_line_altitide smallint NOT NULL,
	accumulation_area_ratio smallint NOT NULL,
	elevation_minimum smallint NOT NULL,
	elevation_maximum smallint NOT NULL,
	remarks varchar(500) NULL,
	reference varchar(500) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE mass_balance.mass_balance ADD CONSTRAINT pk_mass_balance_periode
	PRIMARY KEY (pk)
;

ALTER TABLE mass_balance.mass_balance 
  ADD CONSTRAINT uq_mass_balance_periode_pk UNIQUE (pk)
;

CREATE INDEX "IXFK_mass_balance_analysis_method_type" ON mass_balance.mass_balance (fk_analysis_method ASC)
;

CREATE INDEX "IXFK_mass_balance_glacier" ON mass_balance.mass_balance (fk_glacier ASC)
;

CREATE INDEX ixfk_mass_balance_period_data_embargo_type ON mass_balance.mass_balance (fk_embargo_type ASC)
;


CREATE INDEX ixfk_mass_balance_periode_mass_balance_type ON mass_balance.mass_balance (fk_mass_balance_type ASC)
;


/* Create Foreign Key Constraints */

ALTER TABLE mass_balance.mass_balance ADD CONSTRAINT "FK_mass_balance_analysis_method_type"
	FOREIGN KEY (fk_analysis_method) REFERENCES mass_balance.analysis_method_type (pk) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE mass_balance.mass_balance ADD CONSTRAINT "FK_mass_balance_glacier"
	FOREIGN KEY (fk_glacier) REFERENCES base_data.glacier (pk) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE mass_balance.mass_balance ADD CONSTRAINT fk_mass_balance_period_data_embargo_type
	FOREIGN KEY (fk_embargo_type) REFERENCES administration.data_embargo_type (pk) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE mass_balance.mass_balance ADD CONSTRAINT fk_mass_balance_periode_mass_balance_type
	FOREIGN KEY (fk_mass_balance_type) REFERENCES mass_balance.mass_balance_type (pk) ON DELETE No Action ON UPDATE No Action
;
