/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 02-Aug-2018 16:58:53 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS volume_change.volume_change_analysis_type CASCADE
;

/* Create Tables */

CREATE TABLE volume_change.volume_change_analysis_type
(
	pk smallint NOT NULL,
	short_name varchar(100) NOT NULL,
	description varchar(250) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE volume_change.volume_change_analysis_type ADD CONSTRAINT "PK_volume_change_analysis_type"
	PRIMARY KEY (pk)
;
