/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 11-Jul-2018 16:15:52 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS volume_change.volume_change CASCADE
;

/* Create Tables */

CREATE TABLE volume_change.volume_change
(
	pk uuid NOT NULL,
	fk_glacier uuid NOT NULL,
	date_from date NOT NULL,
	date_to date NOT NULL,
	area_from numeric(10,6) NOT NULL,
	area_to numeric(10,6) NOT NULL,
	elevation_maximum_from numeric(6,2) NOT NULL,
	elevation_minimum_from numeric(6,2) NOT NULL,
	elevation_maximum_to numeric(6,2) NOT NULL,
	elevation_minimum_to numeric(6,2) NOT NULL,
	volume_change numeric(10,6) NOT NULL,
	height_change_mean numeric(5,2) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE volume_change.volume_change ADD CONSTRAINT "PK_volume_change"
	PRIMARY KEY (pk)
;

CREATE INDEX "IXFK_volume_change_glacier" ON volume_change.volume_change (fk_glacier ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE volume_change.volume_change ADD CONSTRAINT "FK_volume_change_glacier"
	FOREIGN KEY (fk_glacier) REFERENCES base_data.glacier (pk) ON DELETE Cascade ON UPDATE Cascade
;
