/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 17-Aug-2018 16:20:37 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS hydrology.stream_basin CASCADE
;

/* Create Tables */

CREATE TABLE hydrology.stream_basin
(
	pk uuid NOT NULL,
	pk_hades integer NOT NULL,
	geom geometry(POLYGON, 4326) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE hydrology.stream_basin ADD CONSTRAINT "PK_stream_basin"
	PRIMARY KEY (pk)
;

CREATE INDEX IXGEOM_stream_basin_geometry ON hydrology.stream_basin 
	USING GIST (geom);
	
CREATE INDEX IXFK_pk_hades ON hydrology.stream_basin (pk_hades ASC);

CREATE INDEX IXFK_stream_basin_pk ON hydrology.stream_basin (pk ASC);

GRANT ALL ON hydrology.stream_basin TO glrw;
GRANT SELECT ON hydrology.stream_basin TO glro;
GRANT SELECT ON hydrology.stream_basin TO gldirw;
GRANT SELECT ON hydrology.stream_basin TO gldiro;