/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0      */
/*  Created On : 15-Jun-2018 13:43:26                   */
/*  DBMS       : PostgreSQL                             */
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS hydrology.stream_basin_type CASCADE
;

/* Create Tables */

CREATE TABLE hydrology.stream_basin_type
(
	pk                   smallint     NOT NULL,
	pk_hades             smallint     NOT NULL,
	name                 varchar(25)  NOT NULL,
	sgi_region_statement varchar(300) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE hydrology.stream_basin_type ADD CONSTRAINT pk_stream_basin_type
	PRIMARY KEY (pk)
;

CREATE INDEX IXFK_stream_basin_type_pk_hades ON hydrology.stream_basin_type (pk_hades ASC);

CREATE INDEX IXFK_stream_basin_type_pk ON hydrology.stream_basin_type (pk ASC);

CREATE INDEX IXFK_stream_basin_type_name ON hydrology.stream_basin_type (name ASC);

ALTER TABLE hydrology.stream_basin_type 
  ADD CONSTRAINT uq_stream_basin_type_pk UNIQUE (pk)
;
