/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 14-Sep-2018 13:40:31 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS administration.position_capture_method_type CASCADE
;

/* Create Tables */

CREATE TABLE administration.position_capture_method_type
(
	pk integer NOT NULL,
	short_name varchar(50) NOT NULL,
	description text NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE administration.position_capture_method_type ADD CONSTRAINT "PK_position_capture_method"
	PRIMARY KEY (pk)
;
