/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 14-Sep-2018 13:44:13 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS administration.person CASCADE
;

/* Create Tables */

CREATE TABLE administration.person
(
	pk uuid NOT NULL,
	name_first varchar(50) NOT NULL,
	name_last varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE administration.person ADD CONSTRAINT pk_person
	PRIMARY KEY (pk)
;

ALTER TABLE administration.person 
  ADD CONSTRAINT uq_person_pk UNIQUE (pk)
;
