/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 14-Sep-2018 13:41:19 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS administration.object_origin_type CASCADE
;

/* Create Tables */

CREATE TABLE administration.object_origin_type
(
	pk          integer NOT NULL,
	short_name  varchar(50) NOT NULL,
	description text NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE administration.object_origin_type ADD CONSTRAINT "PK_object_origin"
	PRIMARY KEY (pk)
;
