/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 14-Sep-2018 13:52:24 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS administration.observer CASCADE
;

/* Create Tables */

CREATE TABLE administration.observer
(
	pk uuid NOT NULL,
	fk_institution uuid NOT NULL,
	fk_person uuid NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE administration.observer ADD CONSTRAINT pk_observer
	PRIMARY KEY (pk)
;

ALTER TABLE administration.observer 
  ADD CONSTRAINT uq_observer_pk UNIQUE (pk)
;

CREATE INDEX ixfk_observer_institution ON administration.observer (fk_institution ASC)
;

CREATE INDEX ixfk_observer_person ON administration.observer (fk_person ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE administration.observer ADD CONSTRAINT fk_observer_institution
	FOREIGN KEY (fk_institution) REFERENCES  administration.institution ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE administration.observer ADD CONSTRAINT fk_observer_person
	FOREIGN KEY (fk_person) REFERENCES  administration.person  ON DELETE Cascade ON UPDATE Cascade
;
