/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 14-Sep-2018 13:43:52 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS administration.institution CASCADE
;

/* Create Tables */

CREATE TABLE administration.institution
(
	pk uuid NOT NULL,
	name varchar(50) NOT NULL,
	departement varchar(50) NOT NULL,
	description text NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE administration.institution ADD CONSTRAINT pk_institution
	PRIMARY KEY (pk)
;

ALTER TABLE administration.institution 
  ADD CONSTRAINT uq_institution_pk UNIQUE (pk)
;
