/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 15-Jun-2018 13:21:24 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS administration.data_embargo_type CASCADE
;

/* Create Tables */

CREATE TABLE administration.data_embargo_type
(
	pk smallint NOT NULL,
	short_name varchar(10) NOT NULL,
	description varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE administration.data_embargo_type ADD CONSTRAINT pk_data_embargo_type
	PRIMARY KEY (pk)
;

ALTER TABLE administration.data_embargo_type 
  ADD CONSTRAINT uq_data_embargo_type_pk UNIQUE (pk)
;
