/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 17-Aug-2018 13:50:35 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS base_data.glaciological_report_region CASCADE
;

/* Create Tables */

CREATE TABLE base_data.glaciological_report_region
(
	pk uuid NOT NULL,
	fk_glacier uuid NOT NULL,
	geom geometry(POLYGON, 4326) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE base_data.glaciological_report_region ADD CONSTRAINT "PK_glaciological_report_region"
	PRIMARY KEY (pk)
;

CREATE INDEX IXFK_glaciological_report_regions_glacier ON base_data.glaciological_report_region (fk_glacier ASC)
;

CREATE INDEX IXFK_glaciological_report_regions_pk ON base_data.glaciological_report_region (pk ASC)
;

CREATE INDEX IXGEOM_glaciological_report_regions_geometry ON base_data.glaciological_report_region 
	USING GIST (geom);

/* Create Foreign Key Constraints */

ALTER TABLE base_data.glaciological_report_region ADD CONSTRAINT "FK_glaciological_report_regions_glacier"
	FOREIGN KEY (fk_glacier) REFERENCES base_data.glacier (pk) ON DELETE Cascade ON UPDATE Cascade
;


GRANT ALL ON base_data.glaciological_report_region TO glrw;
GRANT SELECT ON base_data.glaciological_report_region TO glro;
GRANT SELECT ON base_data.glaciological_report_region TO gldirw;
GRANT SELECT ON base_data.glaciological_report_region TO gldiro;

