/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 14-Sep-2018 13:42:46 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS base_data.outline CASCADE
;

/* Create Tables */

CREATE TABLE base_data.outline
(
	pk uuid NOT NULL,
	fk_glacier uuid NOT NULL,
	fk_observer uuid NOT NULL,
	fk_object_origin_type integer NOT NULL,
	fk_position_capture_method_type integer NOT NULL,
	fk_height_capture_method_type integer NOT NULL,
	fk_object_type integer NOT NULL,
	geom geometry(LINESTRING, 4326) NOT NULL,
	measure_date date NOT NULL
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE base_data.outline ADD CONSTRAINT "PK_outline"
	PRIMARY KEY (pk)
;

CREATE INDEX "IXFK_outline_glacier" ON base_data.outline (fk_glacier ASC)
;

CREATE INDEX "IXFK_outline_height_capture_method_type" ON base_data.outline (fk_height_capture_method_type ASC)
;

CREATE INDEX "IXFK_outline_object_origin_type" ON base_data.outline (fk_object_origin_type ASC)
;

CREATE INDEX "IXFK_outline_object_type" ON base_data.outline (fk_object_type ASC)
;

CREATE INDEX "IXFK_outline_observer" ON base_data.outline (fk_observer ASC)
;

CREATE INDEX "IXFK_outline_position_capture_method_type" ON base_data.outline (fk_position_capture_method_type ASC)
;

CREATE INDEX "IXGEOM_outline_geometry" ON base_data.outline USING GIST (geom);
;

/* Create Foreign Key Constraints */

ALTER TABLE base_data.outline ADD CONSTRAINT "FK_outline_glacier"
	FOREIGN KEY (fk_glacier) REFERENCES base_data.glacier (pk) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE base_data.outline ADD CONSTRAINT "FK_outline_height_capture_method_type"
	FOREIGN KEY (fk_height_capture_method_type) REFERENCES administration.height_capture_method_type (pk) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE base_data.outline ADD CONSTRAINT "FK_outline_object_origin_type"
	FOREIGN KEY (fk_object_origin_type) REFERENCES administration.object_origin_type (pk) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE base_data.outline ADD CONSTRAINT "FK_outline_object_type"
	FOREIGN KEY (fk_object_type) REFERENCES base_data.object_type (pk) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE base_data.outline ADD CONSTRAINT "FK_outline_observer"
	FOREIGN KEY (fk_observer) REFERENCES administration.observer (pk) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE base_data.outline ADD CONSTRAINT "FK_outline_position_capture_method_type"
	FOREIGN KEY (fk_position_capture_method_type) REFERENCES administration.position_capture_method_type (pk) ON DELETE Cascade ON UPDATE Cascade
;

GRANT ALL ON base_data.outline TO glrw;
GRANT SELECT ON base_data.outline TO glro;
GRANT SELECT ON base_data.outline TO gldirw;
GRANT SELECT ON base_data.outline TO gldiro;