UPDATE base_data.glacier SET name ='Gspaltenhorngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'a' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Gamchigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'a' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Morgenhorngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'a' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Glatscher da Sut Fuina' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'b' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Glasergletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Sardonagletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Blüemlisalpgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Obere Oeschinengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Undere Oeschinengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Fründengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Fulegletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Silleregletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Fründenhorn SE' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Kanderfirn N' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '13';
UPDATE base_data.glacier SET name ='Birggletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Lötschegletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Balmhorngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Tellingletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '32';
UPDATE base_data.glacier SET name ='Fanellgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'c' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Firenband' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'c' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Altelsgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'c' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Schwarzgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'c' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Rinderhorngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'c' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Daubenhorngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'c' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Lämmerengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'c' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Wildstrubelgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'c' AND inventory_code = '13';
UPDATE base_data.glacier SET name ='Wildstrubel N' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'c' AND inventory_code = '27';
UPDATE base_data.glacier SET name ='Wildstrubel NE' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'c' AND inventory_code = '28';
UPDATE base_data.glacier SET name ='Scalettagletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '2' AND river_level_0 = 'd' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Ducangletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '2' AND river_level_0 = 'd' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Lorenzhorngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'd' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Läntagletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'd' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Grauhorngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'd' AND inventory_code = '19';
UPDATE base_data.glacier SET name ='Pizolgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'd' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Windgällenfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Stäfelfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Alpgnofer Firn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Ruchenfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Bocktschingelfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Hälsifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Hüfifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Hangfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '26';
UPDATE base_data.glacier SET name ='Brunnifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Staldenfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Stöcklifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '20';
UPDATE base_data.glacier SET name ='Fellelifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '21';
UPDATE base_data.glacier SET name ='Spillauibielfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Spilauifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '24';
UPDATE base_data.glacier SET name ='Stockfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '25';
UPDATE base_data.glacier SET name ='Hangfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'd' AND inventory_code = '26';
UPDATE base_data.glacier SET name ='Strubelgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'd' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Tungelgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 = 'd' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Gältegletscher NE' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 = 'd' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Gältegletscher SW' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 = 'd' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Piotgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'e' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Unter Satzfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Ober Satzgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Schwarzwasserfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Gurschenfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='St. Annafirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Gupisfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '13';
UPDATE base_data.glacier SET name ='Ghiacciaio di Lucendro' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Witenwasserengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '20';
UPDATE base_data.glacier SET name ='Tiefengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '37';
UPDATE base_data.glacier SET name ='Muttengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Wendengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'e' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Uratgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'e' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Steigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'e' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Steilimigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'e' AND inventory_code = '13';
UPDATE base_data.glacier SET name ='Gigligletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'e' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Triftgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'e' AND inventory_code = '24';
UPDATE base_data.glacier SET name ='Tobigergletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'e' AND inventory_code = '27';
UPDATE base_data.glacier SET name ='Leidhorngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '0' AND river_level_0 = 'f' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Vadret da Tisch' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '2' AND river_level_0 = 'f' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glatscher dil Terri' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Glatscher da Gaglianera' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Glatscher dalla Greina' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Glatscher da Valdraus' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Glatscher da Lavaz' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Mittaggletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Blauberggletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Dammagletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Chelengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Steigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Flachensteinfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Wallenburfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '24';
UPDATE base_data.glacier SET name ='Salbitgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '28';
UPDATE base_data.glacier SET name ='Rohrfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '29';
UPDATE base_data.glacier SET name ='Kartigelfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '32';
UPDATE base_data.glacier SET name ='Rütifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '34';
UPDATE base_data.glacier SET name ='Griessenfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '35';
UPDATE base_data.glacier SET name ='Chalchtalfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '40';
UPDATE base_data.glacier SET name ='Sustenlochfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '42';
UPDATE base_data.glacier SET name ='Chli Sustlifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '43';
UPDATE base_data.glacier SET name ='Wichelplanggfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '48';
UPDATE base_data.glacier SET name ='Chüefadfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '50';
UPDATE base_data.glacier SET name ='Sewenzwächten' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '55';
UPDATE base_data.glacier SET name ='Sassfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '59';
UPDATE base_data.glacier SET name ='Leitschachfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '61';
UPDATE base_data.glacier SET name ='Rotfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '68';
UPDATE base_data.glacier SET name ='Maasplanggfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '69';
UPDATE base_data.glacier SET name ='Chüefadfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '51';
UPDATE base_data.glacier SET name ='Gummigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Homadgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Diechtergletscher S' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Alpligletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Gärstengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'f' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Glacier de la Plaine Morte' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'f' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Seegletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '0' AND river_level_0 = 'g' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Silvrettagletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '0' AND river_level_0 = 'g' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Chammgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '0' AND river_level_0 = 'g' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Roggengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '0' AND river_level_0 = 'g' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Vernelagletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '0' AND river_level_0 = 'g' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Zadrellgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '0' AND river_level_0 = 'g' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Jörigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '0' AND river_level_0 = 'g' AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Verstanclagletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '0' AND river_level_0 = 'g' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Vadret digl Ela' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '2' AND river_level_0 = 'g' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Vadrec da Gallagiun' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'g' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Ghiacciaio del Pizzo Rosso' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'g' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Vadrec da la Bles' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'g' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Glatscher dallas Tuors' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'g' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Glatscher da Casatscha' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'g' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Glatscher dil Lai Blau' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'g' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Glatt Firn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Guggitaler Schnee' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Chlitaler Firn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Chesselfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Blüemlisalpfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Schöntaler Firn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '13';
UPDATE base_data.glacier SET name ='Schlittchuechen' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Schlossberggletscher (Erstfeld)' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Chlitaler Firn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '19';
UPDATE base_data.glacier SET name ='Oberaargletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'g' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Tierberggletscher (Guttannen)' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'g' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Unteraargletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'g' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Bächligletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'g' AND inventory_code = '25';
UPDATE base_data.glacier SET name ='Studergletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'g' AND inventory_code = '49';
UPDATE base_data.glacier SET name ='Lauteraargletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'g' AND inventory_code = '52';
UPDATE base_data.glacier SET name ='Glatscher da Puozas' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'h' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glatscher da Gannaretsch' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'h' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Glatscher da Nalps' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'h' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Alplifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'h' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Firenband' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'h' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Firnalpeligletscher NW' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'h' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Titlisgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'h' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Golegg-Gletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'h' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Wiissenbachgletscher E' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'h' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Glatscher da Curnera' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'i' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Hinter Sulzfirngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'i' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Limmerngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'i' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Plattalva' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'i' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Langfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'i' AND inventory_code = '21';
UPDATE base_data.glacier SET name ='Grienbärgligletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'i' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Gauligletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'i' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Ränfengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'i' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Schwarzhorngletscher (Splügen)' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'j' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Glatscher da Strem' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'j' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Iswändli' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'j' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Rosenlouwigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'j' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Blau Gletscherli' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'j' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Tambogletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'k' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Glärnischfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'k' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Vadret da Piz Platta' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '2' AND river_level_0 = 'l' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Ghiacciaio del Tambo' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'l' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Ghiacciaio de la Curciusa' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'l' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Glatscher da Cavrein' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Glatscher da Gliems' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '22';
UPDATE base_data.glacier SET name ='Gutzlgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Chrinnengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Wächselgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Nässigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Schreckfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Lauteraargletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '22';
UPDATE base_data.glacier SET name ='Wächselgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Ischmeer' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '32';
UPDATE base_data.glacier SET name ='Challfirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '38';
UPDATE base_data.glacier SET name ='Glatscher da Punteglias' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Hängegletscher Eiger Westgrat' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Eigergletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Guggigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Giessengletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Silberhorngletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Rottalgletscher (Lauterbrunnen)' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Vordra Schmadrigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Hindra Schmadrigletscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Schadrifirn' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Chielouwenenlgetscher' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '27';
UPDATE base_data.glacier SET name ='Zapportgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'n' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Paradiesgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'n' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Glatscher da Gavirolas' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'n' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Glatscher da Fluaz' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'n' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Glatscher da Mer' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'n' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Höhberggletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'o' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Chilchalpgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '3' AND river_level_0 = 'o' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Vorabgletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'p' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glatschiu dil Segnas' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'p' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Taminser Gletscher' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = 'p' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Chüealpgletscher' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Glacier du Sex Rouge' WHERE river_level_3 = 'B' AND river_level_2 = '1' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glacier de Paneirosse' WHERE river_level_3 = 'B' AND river_level_2 = '1' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Grand Plan Névé' WHERE river_level_3 = 'B' AND river_level_2 = '1' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Petit Plan Névé' WHERE river_level_3 = 'B' AND river_level_2 = '1' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Glacier des Martinets' WHERE river_level_3 = 'B' AND river_level_2 = '1' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Plan Névé' WHERE river_level_3 = 'B' AND river_level_2 = '1' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Glacier des Diablerets' WHERE river_level_3 = 'B' AND river_level_2 = '2' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Glacier de Zanfleuron' WHERE river_level_3 = 'B' AND river_level_2 = '2' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glacier du Brotsé' WHERE river_level_3 = 'B' AND river_level_2 = '2' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Flüeggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '2' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Dalagletscher' WHERE river_level_3 = 'B' AND river_level_2 = '2' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Majinggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '2' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Oberferdengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Ferdengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Milibachgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Dischliggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Langletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Dischliggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Loibinblachgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Innre Stampbachgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Uistre Stampbachgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Birchgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Hangendegletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Üssre Baltschieder' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Joligletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Üssre Baltschiedergletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Innre Baltschiedergletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Beichgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Oberaletschgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Unterbächgletscher NE' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Beichgrat SE 1' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Beichgrat SE 2' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Distelgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Oberaletschfirn' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Driestgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Zenbächengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Mittelaletschgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '21';
UPDATE base_data.glacier SET name ='Grosser Aletschgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '26';
UPDATE base_data.glacier SET name ='Äbeni Flue S' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '27';
UPDATE base_data.glacier SET name ='Kranzbergfirn' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '28';
UPDATE base_data.glacier SET name ='Schönbühlgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '31';
UPDATE base_data.glacier SET name ='Schönbühlgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '56';
UPDATE base_data.glacier SET name ='Bächligletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Minstigergletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Im Sumpf' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Rhonegletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Galengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Muttgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Saasgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Gerengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Chüebodengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '20';
UPDATE base_data.glacier SET name ='Ritzgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Fallgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Turbegletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Mittlebärggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Schingletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Helsegletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Mättitalgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '22';
UPDATE base_data.glacier SET name ='Rappegletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '25';
UPDATE base_data.glacier SET name ='Steinugletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Bortelgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Chaltwassergletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Gamsagletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Fletschhorngletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Lagginhorngletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Mälligagletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Wysstalgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Furggengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Ofentalgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Tällibodengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '20';
UPDATE base_data.glacier SET name ='Seewjinengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '22';
UPDATE base_data.glacier SET name ='Hangendegletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '27';
UPDATE base_data.glacier SET name ='Allalingletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '29';
UPDATE base_data.glacier SET name ='Hohlaubgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '32';
UPDATE base_data.glacier SET name ='Findelgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '65';
UPDATE base_data.glacier SET name ='Fallgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Hohbalmgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Bidergletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Riedgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Dirrugletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Hobärggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Festiggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Alphubelgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Triftjgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Adlergletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Monte Rosagletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Grenzgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Oberer Theodulgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '30';
UPDATE base_data.glacier SET name ='Furgggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '31';
UPDATE base_data.glacier SET name ='Matterhorngletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Zmuttgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Hohwänggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Gabelhorgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Tiefenmattengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '20';
UPDATE base_data.glacier SET name ='Gabelhorngletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Glacier de l''Obergabelhorn' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '7' AND river_level_0 = '' AND inventory_code = '24';
UPDATE base_data.glacier SET name ='Hohlichtgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Schmalgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Bisgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Rossgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Holzgletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Abberggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Schölligletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '13';
UPDATE base_data.glacier SET name ='Undere Stelligletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Obere Stelligletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Junggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '8' AND river_level_0 = '' AND inventory_code = '19';
UPDATE base_data.glacier SET name ='Brändjigletscher' WHERE river_level_3 = 'B' AND river_level_2 = '6' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Holesteigletscher' WHERE river_level_3 = 'B' AND river_level_2 = '6' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Diablons Gletscher' WHERE river_level_3 = 'B' AND river_level_2 = '6' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Bruneggletscher' WHERE river_level_3 = 'B' AND river_level_2 = '6' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '20';
UPDATE base_data.glacier SET name ='Bella Tola Gletscher' WHERE river_level_3 = 'B' AND river_level_2 = '6' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Glacier du Besso' WHERE river_level_3 = 'B' AND river_level_2 = '6' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Glacier de Zinal' WHERE river_level_3 = 'B' AND river_level_2 = '6' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Glacier du Mourti' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Glacier de Bricola' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Glacier de la Dent Blance' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Glacier des Manzettes' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Glacier de Ferpècle' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Glacier de l''Aiguille' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Glacier due Montay' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Le Biegnet' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '19';
UPDATE base_data.glacier SET name ='Glacier des Rosses' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Glacier de Tsarmine' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glacier de la Tsa' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Glacier des Douves Blanches' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Glacier de Bertol' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Haute Glacier d''Arolla' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Bas Glacier d''Arolla' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Glacier de Pièce' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Glacier des Ignes' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '21';
UPDATE base_data.glacier SET name ='Glacier Inférieur des Aiguilles Rouges' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '22';
UPDATE base_data.glacier SET name ='Glacier de Merderé' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glacier de Zaudric' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Glacier de Cheilon' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Glacier de la Luette' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Glacer de l''En Darray' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Glacier des Ecoulaies' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Glacier de Mourti' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Glacier de Prafleuri' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Glacier de Métail' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '20';
UPDATE base_data.glacier SET name ='Glacier d''Orchère' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '22';
UPDATE base_data.glacier SET name ='Glacier du Giétro' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Grand Désert' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Glacier du Petit Mont Fort' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Glacier du Mont Fort' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Glacier des Louettes Econdouè' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '13';
UPDATE base_data.glacier SET name ='Glacier de la Chaux' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Glacier de Sovereu' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Glacier du Parrain' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Glacier du Crêt' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Glacier du Giétro' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Glacier de Lire Rose' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Glacier de la Ruinette' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Glacier du Brenay' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '19';
UPDATE base_data.glacier SET name ='Glacier de la Grande Lire' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '21';
UPDATE base_data.glacier SET name ='Glacier d''Epicoune' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '30';
UPDATE base_data.glacier SET name ='Glacier de Crête Sèche' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '33';
UPDATE base_data.glacier SET name ='Glacier de Fenêtre' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '34';
UPDATE base_data.glacier SET name ='Glacier du Mont Durand' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '36';
UPDATE base_data.glacier SET name ='Glacier du Tournelon Blanc' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '44';
UPDATE base_data.glacier SET name ='Glacier de Bocheresse' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '45';
UPDATE base_data.glacier SET name ='Glacier du Grand Combin' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '48';
UPDATE base_data.glacier SET name ='Glacier des Follâts' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Glacier Pendant' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Glacier de Boveire' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Glacier de la Trouye' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Glacier du Meltin' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Glacier du Sonadon' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Glacier de Valsorey' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Glacier du Tseudet' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Glacier du Vélan' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Glacier de Pieudet' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '19';
UPDATE base_data.glacier SET name ='Glacier de Pro' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '20';
UPDATE base_data.glacier SET name ='Dôme de Vélan' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '21';
UPDATE base_data.glacier SET name ='Plateau des Maisons Blanches' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '22';
UPDATE base_data.glacier SET name ='Glacier des Angroniettes' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glacier du Dolent' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Glacier de Treutsebo' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Glacier des Planereuses' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '13';
UPDATE base_data.glacier SET name ='Glacier de l''Evole E' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Glacier des Plines' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Glacier des Ravines Rousses' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '20';
UPDATE base_data.glacier SET name ='Glacier d''Orny' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Glacier de Saleinaz' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Glacier d''Arpette' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glacier du Trient' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Glacier des Grands' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Glacier des Berons' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Glacier des Petoudes' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Glacier de la Fenive' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Glacier des Rosses' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Glacier des Fonds' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Glacier Noir' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Glacier de Chalin' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Glacier de Sol' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Grande Pente' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Glacier des Ottans' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Zwischenbergengletscher' WHERE river_level_3 = 'C' AND river_level_2 = '0' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Weissmiesgletscher' WHERE river_level_3 = 'C' AND river_level_2 = '0' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Laggingletscher' WHERE river_level_3 = 'C' AND river_level_2 = '0' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Holutriftgletscher' WHERE river_level_3 = 'C' AND river_level_2 = '0' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Sibifluegletscher' WHERE river_level_3 = 'C' AND river_level_2 = '0' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Bodmergletscher' WHERE river_level_3 = 'C' AND river_level_2 = '0' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Griessernugletscher' WHERE river_level_3 = 'C' AND river_level_2 = '0' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Alpjergletscher' WHERE river_level_3 = 'C' AND river_level_2 = '0' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Ghiacciaio del Cavagnöö' WHERE river_level_3 = 'C' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Ghiacciaio Grande di Croslina' WHERE river_level_3 = 'C' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Ghiacciaio Piccolo di Croslina' WHERE river_level_3 = 'C' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Ghiacciaio di Val Torta' WHERE river_level_3 = 'C' AND river_level_2 = '3' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Ghiacciaio di Valleggia' WHERE river_level_3 = 'C' AND river_level_2 = '3' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Ghiacciaio del Corno' WHERE river_level_3 = 'C' AND river_level_2 = '3' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Ghiacciaio di Pesciora' WHERE river_level_3 = 'C' AND river_level_2 = '3' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Vadrecc di Camadra' WHERE river_level_3 = 'C' AND river_level_2 = '4' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Vadrecc di Sorda' WHERE river_level_3 = 'C' AND river_level_2 = '4' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Vadrecc di Casletto' WHERE river_level_3 = 'C' AND river_level_2 = '4' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Vadrecc di Bi Bresciana' WHERE river_level_3 = 'C' AND river_level_2 = '4' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Ghiacciaio di Giumello' WHERE river_level_3 = 'C' AND river_level_2 = '4' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Ghiacciaio di Piotta' WHERE river_level_3 = 'C' AND river_level_2 = '4' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Ghiacciaio di Alto' WHERE river_level_3 = 'C' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Ghiacciaio di Basso' WHERE river_level_3 = 'C' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Ghiacciaio de Stabi' WHERE river_level_3 = 'C' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Vadret Dei Rossi' WHERE river_level_3 = 'C' AND river_level_2 = '8' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Vadrec del Forno' WHERE river_level_3 = 'C' AND river_level_2 = '8' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Vadrec dal Cantun' WHERE river_level_3 = 'C' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Vadrec dal Castel Nord' WHERE river_level_3 = 'C' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '13';
UPDATE base_data.glacier SET name ='Vadrec dal Castel Sud' WHERE river_level_3 = 'C' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Vadrec da l''Albigna' WHERE river_level_3 = 'C' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Vadrec da la Bondasca' WHERE river_level_3 = 'C' AND river_level_2 = '8' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret da Canton' WHERE river_level_3 = 'C' AND river_level_2 = '9' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Vadret da Palü' WHERE river_level_3 = 'C' AND river_level_2 = '9' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Vadret da Sassal Mason' WHERE river_level_3 = 'C' AND river_level_2 = '9' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Vadret dal Cambrena' WHERE river_level_3 = 'C' AND river_level_2 = '9' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Vadreit da Camp' WHERE river_level_3 = 'C' AND river_level_2 = '9' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Vadret da Triazza' WHERE river_level_3 = 'E' AND river_level_2 = '0' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Vadret da Lischana' WHERE river_level_3 = 'E' AND river_level_2 = '0' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret da Sesvenna' WHERE river_level_3 = 'E' AND river_level_2 = '0' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Vadret da Zuort' WHERE river_level_3 = 'E' AND river_level_2 = '0' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Vadret d''Arlas' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Vadret da Morteratsch' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Vadret Prievlus' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret Boval Dadour' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Vadret da Misaun' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Vadrettin da Tschierva' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Vadret da Tschierva' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret da Roseg' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Vadret dal Capütschin' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Vadret dal Murtel' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Vadret da l''Alp Ota' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Vadret da Rosatsch' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Vadret da Murtèl' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Vadrettin dal Capütschin' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Vadret dal Tremoggia' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Vadret da Fex' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret dal Güz' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Vadrec da Fedoz' WHERE river_level_3 = 'E' AND river_level_2 = '2' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Vadret Lagrev' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Vadret Güglia' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '3' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Vadret Palüd Marscha' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Vadret Giüna' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret dal Giaviöl' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Vadret Traunter Ovas' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Vadret d''Agnel' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Vadret Calderas' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Vadret Laviner' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '5' AND river_level_0 = '' AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Vadret Pischa' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Vadret d''Es-cha' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Vadret Viluoch' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Vadret Scaletta' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Vadret Vallorgia' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Vadret da Radönt' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Vadret Valtorta' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret Sagliains' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '2';
UPDATE base_data.glacier SET name ='Vadret da las Maisas' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret Tiatscha' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = '' AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Plain Rai' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Vadret Tuoi' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret d''Urezzas' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Vadret da Chalaus' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Vadret Futschöl' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 = '' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Vadret da Tasna' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = '' AND inventory_code = '1';