UPDATE base_data.glacier SET name ='Vadret Pischa W' WHERE river_level_3 = 'A' AND river_level_2 = '1' AND river_level_1 = '2' AND river_level_0 = 'e' AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Piz Kesch SW' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'i' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Clariden N' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'j' AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Bös Fulen E' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'j' AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Ortstock NE' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '0' AND river_level_0 = 'j' AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Gross Ruchen ' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'c' AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Pizzo di Frodo' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Gemsstock E' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'e' AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Grassengrat S 1' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '78';
UPDATE base_data.glacier SET name ='Grassengrat S 2' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'f' AND inventory_code = '85';
UPDATE base_data.glacier SET name ='Krönten N' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 = 'g' AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Schafegg S' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'e' AND inventory_code = '25';
UPDATE base_data.glacier SET name ='Mitellegi' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'l' AND inventory_code = '40';
UPDATE base_data.glacier SET name ='Breithorn N' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 = 'm' AND inventory_code = '61';
UPDATE base_data.glacier SET name ='Fründenhorn SE' WHERE river_level_3 = 'A' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 = 'b' AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Ferdenrothorn E' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '0' AND river_level_0 ISNULL AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Tschingelhorn (Blatten)' WHERE river_level_3 = 'B' AND river_level_2 = '3' AND river_level_1 = '0' AND river_level_0 ISNULL AND inventory_code = '25';
UPDATE base_data.glacier SET name ='Wasenhorn E' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '1' AND river_level_0 ISNULL AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Oberlicke SE' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '1' AND river_level_0 ISNULL AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Galengletscher' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '3' AND river_level_0 ISNULL AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Mittaghorn N' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '5' AND river_level_0 ISNULL AND inventory_code = '10';
UPDATE base_data.glacier SET name ='Blinnjoch' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '5' AND river_level_0 ISNULL AND inventory_code = '33';
UPDATE base_data.glacier SET name ='Turbhorn ' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 ISNULL AND inventory_code = '3';
UPDATE base_data.glacier SET name ='Punta Dèvero ' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '6' AND river_level_0 ISNULL AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Furggubäumlicke' WHERE river_level_3 = 'B' AND river_level_2 = '4' AND river_level_1 = '7' AND river_level_0 ISNULL AND inventory_code = '8';
UPDATE base_data.glacier SET name ='Triftgrat NW' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 ISNULL AND inventory_code = '15';
UPDATE base_data.glacier SET name ='Triftgrat SE' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Gross Bigerhorn SE 1' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '3' AND river_level_0 ISNULL AND inventory_code = '27';
UPDATE base_data.glacier SET name ='Gross Bigerhorn SE 2' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '4' AND river_level_0 ISNULL AND inventory_code = '5';
UPDATE base_data.glacier SET name ='Hobärghorn W' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '5' AND river_level_0 ISNULL AND inventory_code = '39';
UPDATE base_data.glacier SET name ='Kleiner Pollux' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '6' AND river_level_0 ISNULL AND inventory_code = '24';
UPDATE base_data.glacier SET name ='Wellenkuppe' WHERE river_level_3 = 'B' AND river_level_2 = '5' AND river_level_1 = '7' AND river_level_0 ISNULL AND inventory_code = '25';
UPDATE base_data.glacier SET name ='Stierbärg' WHERE river_level_3 = 'B' AND river_level_2 = '6' AND river_level_1 = '0' AND river_level_0 ISNULL AND inventory_code = '23';
UPDATE base_data.glacier SET name ='Pointes de Tsenâ Réfien' WHERE river_level_3 = 'B' AND river_level_2 = '7' AND river_level_1 = '4' AND river_level_0 ISNULL AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Mont Avril E' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '47';
UPDATE base_data.glacier SET name ='Grand Tavé' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '49';
UPDATE base_data.glacier SET name ='Tournelon Blanc' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '50';
UPDATE base_data.glacier SET name ='Col de Crête Sèche' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '52';
UPDATE base_data.glacier SET name ='Glacier du Tournelon Blanc W' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '3' AND river_level_0 ISNULL AND inventory_code = '16';
UPDATE base_data.glacier SET name ='Tournelon Blanc N' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '3' AND river_level_0 ISNULL AND inventory_code = '17';
UPDATE base_data.glacier SET name ='Tournelon Blanc W' WHERE river_level_3 = 'B' AND river_level_2 = '8' AND river_level_1 = '3' AND river_level_0 ISNULL AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Sé Blanc' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '11';
UPDATE base_data.glacier SET name ='Pointe des Rosses' WHERE river_level_3 = 'B' AND river_level_2 = '9' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Tamierhorn' WHERE river_level_3 = 'C' AND river_level_2 = '1' AND river_level_1 = '4' AND river_level_0 ISNULL AND inventory_code = '4';
UPDATE base_data.glacier SET name ='Lavina di Croslina' WHERE river_level_3 = 'C' AND river_level_2 = '3' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '7';
UPDATE base_data.glacier SET name ='Pass di Caciadur' WHERE river_level_3 = 'C' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 ISNULL AND inventory_code = '6';
UPDATE base_data.glacier SET name ='Ago di Sciora' WHERE river_level_3 = 'C' AND river_level_2 = '8' AND river_level_1 = '4' AND river_level_0 ISNULL AND inventory_code = '18';
UPDATE base_data.glacier SET name ='Piz Varuna E' WHERE river_level_3 = 'C' AND river_level_2 = '9' AND river_level_1 = '3' AND river_level_0 ISNULL AND inventory_code = '1';
UPDATE base_data.glacier SET name ='Piz Traunter Ovas N' WHERE river_level_3 = 'E' AND river_level_2 = '3' AND river_level_1 = '5' AND river_level_0 ISNULL AND inventory_code = '14';
UPDATE base_data.glacier SET name ='Vadret Pischa E' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '1' AND river_level_0 ISNULL AND inventory_code = '93';
UPDATE base_data.glacier SET name ='Scalettahorn S' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '9';
UPDATE base_data.glacier SET name ='Piz da l''Hom' WHERE river_level_3 = 'E' AND river_level_2 = '4' AND river_level_1 = '2' AND river_level_0 ISNULL AND inventory_code = '12';
UPDATE base_data.glacier SET name ='Fuorcla da Vermunt' WHERE river_level_3 = 'E' AND river_level_2 = '5' AND river_level_1 = '1' AND river_level_0 ISNULL AND inventory_code = '4';