/* ---------------------------------------------------- */
/*  Generated by Elias Hodel                 		*/
/*  Created On : 21.02.2020          				*/
/*  DBMS       : PostgreSQL, GLAMOS-DB				*/
/* ---------------------------------------------------- */


DROP TABLE IF EXISTS glacier_hazard.event2damage_type CASCADE
;

/* Create Tables */

CREATE TABLE glacier_hazard.event2damage_type
(
	fk_event uuid NOT NULL,
	fk_damage_type smallint NOT NULL

);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE glacier_hazard.event2damage_type ADD CONSTRAINT pk_event2damage_type
	PRIMARY KEY (fk_event,fk_damage_type);

ALTER TABLE glacier_hazard.event2damage_type 
  ADD CONSTRAINT uq_event2damage_type_pk UNIQUE (fk_event,fk_damage_type);