/* ---------------------------------------------------- */
/*  Generated by Elias Hodel                 		*/
/*  Created On : 21.02.2020          				*/
/*  DBMS       : PostgreSQL, GLAMOS-DB				*/
/* ---------------------------------------------------- */


DROP TABLE IF EXISTS glacier_hazard.geometries CASCADE
;

/* Create Tables */

CREATE TABLE glacier_hazard.geometries
(
	pk uuid NOT NULL,
	geom geometry(LINESTRING, 4326) NOT NULL,
	symbology smallint
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE glacier_hazard.geometries ADD CONSTRAINT pk_geometries
	PRIMARY KEY (pk);

ALTER TABLE glacier_hazard.geometries 
  ADD CONSTRAINT uq_geometries_pk UNIQUE (pk);