/* ---------------------------------------------------- */
/*  Generated by Elias Hodel                 		*/
/*  Created On : 21.02.2020          				*/
/*  DBMS       : PostgreSQL, GLAMOS-DB				*/
/* ---------------------------------------------------- */


DROP TABLE IF EXISTS glacier_hazard.publication CASCADE
;

/* Create Tables */

CREATE TABLE glacier_hazard.publication
(
	pk uuid NOT NULL,
	author varchar(100) NOT NULL,
	date_of_publication varchar(20) NOT NULL,
	title varchar(250) NOT NULL,
	citation varchar(300) NOT NULL

);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE glacier_hazard.publication ADD CONSTRAINT pk_publication
	PRIMARY KEY (pk);

ALTER TABLE glacier_hazard.publication 
  ADD CONSTRAINT uq_publication_pk UNIQUE (pk);