/* ---------------------------------------------------- */
/*  Generated by Elias Hodel                 		*/
/*  Created On : 11.03.2020          				*/
/*  DBMS       : PostgreSQL, GLAMOS-DB				*/
/* ---------------------------------------------------- */

CREATE OR REPLACE VIEW glacier_hazard.web_event_summary AS
	SELECT 
			row_number() OVER() AS gid,
			MIN(vwg.name)			AS glacier_name,
			ST_Union(vwg.geom)      AS geom,
			MIN(vwg.start_year)		AS start_year,
			MIN(vwg.end_year)   AS end_year,
			STRING_AGG(distinct vwg.hazard_maintype, ', ') AS hazard_maintype,
			STRING_AGG(distinct vwg.hazard_subtype, ', ') AS hazard_subtype,
			STRING_AGG(distinct vwg.damage_maintype, ', ') AS damage_maintype,
			STRING_AGG(distinct vwg.damage_subtype, ', ') AS damage_subtype,
			STRING_AGG(distinct vwg.damage_detailtype, ', ') AS damage_detailtype,
			vwg.e_pk                AS pk_event
					

	FROM glacier_hazard.vw_geometries AS vwg
	GROUP BY vwg.e_pk
	ORDER BY glacier_name ASC, start_year asc;


GRANT ALL ON TABLE glacier_hazard.web_event_summary TO gladmin;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE glacier_hazard.web_event_summary TO glrw;
GRANT SELECT ON TABLE glacier_hazard.web_event_summary TO glro;