/* ---------------------------------------------------- */
/*  Generated by Elias Hodel                 		*/
/*  Created On : 21.02.2020          				*/
/*  DBMS       : PostgreSQL, GLAMOS-DB				*/
/* ---------------------------------------------------- */

CREATE OR REPLACE VIEW glacier_hazard.vw_geometries AS
	SELECT 
			row_number() OVER() AS gid,
			g.pk                AS pk,
			e2g.fk_event        AS e2g_fk_event,
			e2g.fk_geometries   AS e2g_fk_geometries,
			e.pk                AS e_pk,
			g.geom              AS geom,
			e.start_year        AS start_year,
			dt.pk AS dt_pk,
			dt.damage_subtype_name AS dt_subtype,
			gl.name_full   AS name
			

	FROM glacier_hazard.geometries AS g

	LEFT JOIN glacier_hazard.event2geometries AS e2g ON 
			(g.pk = e2g.fk_geometries)
	LEFT JOIN glacier_hazard.event AS e ON 
			(e2g.fk_event = e.pk)
	LEFT JOIN glacier_hazard.event2damage_type AS e2dt ON 
			(e.pk = e2dt.fk_event)
	LEFT JOIN glacier_hazard.damage_type AS dt ON 
			(e2dt.fk_damage_type = dt.pk)
	LEFT JOIN base_data.vw_glacier AS gl ON 
			(e.fk_glacier = gl.pk);

GRANT SELECT ON base_data.vw_outline TO glro;
GRANT SELECT ON base_data.vw_outline TO glrw;