/* ---------------------------------------------------- */
/*  Generated by Elias Hodel                 		*/
/*  Created On : 21.02.2020          				*/
/*  DBMS       : PostgreSQL, GLAMOS-DB				*/
/* ---------------------------------------------------- */

DROP TABLE IF EXISTS glacier_hazard.event CASCADE
;

/* Create Tables */

CREATE TABLE glacier_hazard.event
(
	pk uuid NOT NULL,
	fk_glacier uuid NOT NULL,
	start_year varchar(4),
	start_month varchar(2),
	start_day varchar(2),
	start_time varchar(5),
	start_text varchar(25),
    end_year varchar(4),
	end_month varchar(2),
	end_day varchar(2),
	end_time varchar(5),
	end_text varchar(25),
	volume_m3 varchar(50),
	area_damaged_m2 varchar(20),
	dead_people smallint,
	injured_people smallint,
	description_de text,
	description_en text,
	secondary_source varchar(250)

);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE glacier_hazard.event ADD CONSTRAINT pk_event
	PRIMARY KEY (pk);

ALTER TABLE glacier_hazard.event
  ADD CONSTRAINT uq_event_pk UNIQUE (pk);
  
/* Create Foreign Key Constraints */

ALTER TABLE glacier_hazard.event ADD CONSTRAINT "FK_event_glacier"
	FOREIGN KEY (fk_glacier) REFERENCES base_data.glacier (pk) ON DELETE Cascade ON UPDATE Cascade
;