/* ---------------------------------------------------- */
/*  Generated by Elias Hodel                 		*/
/*  Created On : 21.02.2020          				*/
/*  DBMS       : PostgreSQL, GLAMOS-DB				*/
/* ---------------------------------------------------- */


DROP TABLE IF EXISTS glacier_hazard.damage_type CASCADE
;

/* Create Tables */

CREATE TABLE glacier_hazard.damage_type
(
	pk smallint NOT NULL,
	damage_maintype_id smallint NOT NULL,
	damage_maintype_name varchar(100) NOT NULL,
	damage_maintype_desc varchar(250),
	damage_subtype_id smallint,
	damage_subtype_name varchar(100),
	damage_subtype_desc varchar(250),
	damage_detailtype_id smallint,
	damage_detailtype_name varchar(100),
	damage_detailtype_desc varchar(250)
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE glacier_hazard.damage_type ADD CONSTRAINT pk_damage_type
	PRIMARY KEY (pk);

ALTER TABLE glacier_hazard.damage_type 
  ADD CONSTRAINT uq_damage_type_pk UNIQUE (pk);