/* ---------------------------------------------------- */
/*  Generated by Elias Hodel                 		*/
/*  Created On : 21.02.2020          				*/
/*  DBMS       : PostgreSQL, GLAMOS-DB				*/
/* ---------------------------------------------------- */


DROP TABLE IF EXISTS glacier_hazard.event2publication CASCADE
;

/* Create Tables */

CREATE TABLE glacier_hazard.event2publication
(
	fk_event uuid NOT NULL,
	fk_publication uuid NOT NULL

);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE glacier_hazard.event2publication ADD CONSTRAINT pk_event2publication
	PRIMARY KEY (fk_event,fk_publication);

ALTER TABLE glacier_hazard.event2publication 
  ADD CONSTRAINT uq_event2publication_pk UNIQUE (fk_event,fk_publication);