/* ---------------------------------------------------- */
/*  Generated by Elias Hodel                 		*/
/*  Created On : 21.02.2020          				*/
/*  DBMS       : PostgreSQL, GLAMOS-DB				*/
/* ---------------------------------------------------- */

DROP TABLE IF EXISTS glacier_hazard.hazard_type CASCADE
;

/* Create Tables */

CREATE TABLE glacier_hazard.hazard_type
(
	pk smallint NOT NULL,
	hazard_maintype_id smallint NOT NULL,
	hazard_maintype_name varchar(100) NOT NULL,
	hazard_maintype_desc varchar(250),
	hazard_subtype_id smallint NOT NULL,
	hazard_subtype_name varchar(100) NOT NULL,
	hazard_subtype_desc varchar(500)
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE glacier_hazard.hazard_type ADD CONSTRAINT pk_hazard_type
	PRIMARY KEY (pk);

ALTER TABLE glacier_hazard.hazard_type 
  ADD CONSTRAINT uq_hazard_type_pk UNIQUE (pk);