-- event
INSERT INTO glacier_hazard.event(pk, fk_glacier, start_year, start_month, start_day, start_time, start_text, end_year, end_month, end_day, end_time, end_text, volume_m3, area_damaged_m2, dead_people, injured_people, description_de, description_en, secondary_source)VALUES('b26b373c-a237-11ed-a8fc-0242ac120002','7f35fb30-4ec8-11e8-bc7b-985fd331b2ee','2022', '05', '27','' ,'' , '2022', '05', '27','' ,'' ,'' ,'' , 2, 9, 'Ein Eissturz in den frühen Morgenstunden in der Aufsiegsroute ‘Voie du Gardien’ erfasste 17 Alpinisten. Gemäss ersten Berichte forderte er 2 Tote und 7 Verletzte.', 'Medienberichterstattung: https://www.tagesanzeiger.ch/mehrere-menschen-durch-eissturz-am-grand-combin-verletzt-308873928145, https://www.watson.ch/schweiz, /polizeirapport/330854030-7-helikopter-im-einsatz-gletscherabbruch-im-wallis-fordert-2-todesopfer','GLAMOS');
INSERT INTO glacier_hazard.event(pk, fk_glacier, start_year, start_month, start_day, start_time, start_text, end_year, end_month, end_day, end_time, end_text, volume_m3, area_damaged_m2, dead_people, injured_people, description_de, description_en, secondary_source)VALUES('b26b3aa2-a237-11ed-a8fc-0242ac120002','823669f0-4ec8-11e8-880f-985fd331b2ee','2022', '06', '26','' ,'','2022','06','26','' ,'', 'ca. 15000','' , NULL ,NULL , 'Ein Teil einer auf rund 90''000 m3 geschaetzten instablen Masse im Haengegletscher ist abgebrochen und wurde von Touristen in einem Video festgehalten.  Die alpinistische Route zum Weissmies ist im Auslaufbereich.', 'Fotos Acam Geopraevent, Info Gemeinde Saas-Grund, Media (https://www.lenouvelliste.ch/valais/haut-valais/saas-fee/valais-effondrement-spectaculaire-sur-le-glacier-de-trift-une-video-capture-linstant-1195973)','GLAMOS');
INSERT INTO glacier_hazard.event(pk, fk_glacier, start_year, start_month, start_day, start_time, start_text, end_year, end_month, end_day, end_time, end_text, volume_m3, area_damaged_m2, dead_people, injured_people, description_de, description_en, secondary_source)VALUES('b26b3c50-a237-11ed-a8fc-0242ac120002','7f3dc35e-4ec8-11e8-a401-985fd331b2ee','2022', '08', '27','' ,'','2022','08','27','' ,'','' , '',NULL ,NULL , 'Am Nachmittag (ca 17uhr) ereignete sich am Tournelon Blanc ein Wassertaschenausbruch, dessen Wasserschwall im Bach La Lia die Fahrstrasse entlang dem orographisch linken Ufer am Lac de Mauvoisin erreichte.  Ausbruchsvolumen unbekannt, Ausuferung und kleinere Schäden im Bereich der Brücke an der Strasse.', 'Info mit Fotos von Vincent May, Bergführer aus Fionnay der am Rekoflug am Folgetag bei schlechter Witterung teilnahm.  Eireignisdokumentation durch Verantwortliche des Kanton Wallis','GLAMOS');
INSERT INTO glacier_hazard.event(pk, fk_glacier, start_year, start_month, start_day, start_time, start_text, end_year, end_month, end_day, end_time, end_text, volume_m3, area_damaged_m2, dead_people, injured_people, description_de, description_en, secondary_source)VALUES('b26b3dea-a237-11ed-a8fc-0242ac120002','7f6f33a1-4ec8-11e8-88b8-985fd331b2ee','2022', '07', '09','' ,'','2022','07','28','' ,'', 'ca. 800000','' ,NULL ,NULL , 'Die jährliche Entleerung des Lac des Faverges begann in der Nacht vom 9. auf den 10. Juli 2022 durch subglaziale Kanäle. Während der Seespiegel in den ersten Tagen relativ schnell sank (1-1.5m pro Tag) stabilisierte sich der Ausfluss immer mehr und ein kleiner Gletschersee blieb (zum ersten Mal) bis zum Ende der Schmelzperiode bestehen. Während der maximale Seespiegel durch den künstlichen Kanal limitiert wurde, hatte dieser beim Seeausbruch kaum einen grossen Einfluss. Der Seeausbruch selbst ist (im Vergleich zu anderen Jahren) durch sehr moderate Abflusswerte charakterisiert. Während der ersten Tage dürften 1.5-2 m3/s zusätzlich ins System gelangt sein, was nur einem geringen Anstieg der Gesamt-Abflussmengen entspricht. Trotzdem wurden die Wanderwege im Bereich der Simmenfälle durch die lokalen Behörden vorsorglich gesperrt.', 'Infos gemäss Seepegel und Webcam des Geopraevent Datenportals. Ereignisdokumentation von Geotest AG.','GLAMOS');


-- event2damage_type
INSERT INTO glacier_hazard.event2damage_type(fk_event, fk_damage_type) VALUES ('b26b373c-a237-11ed-a8fc-0242ac120002',110);
INSERT INTO glacier_hazard.event2damage_type(fk_event, fk_damage_type) VALUES ('b26b373c-a237-11ed-a8fc-0242ac120002',120);
INSERT INTO glacier_hazard.event2damage_type(fk_event, fk_damage_type) VALUES ('b26b3aa2-a237-11ed-a8fc-0242ac120002',300);
INSERT INTO glacier_hazard.event2damage_type(fk_event, fk_damage_type) VALUES ('b26b3c50-a237-11ed-a8fc-0242ac120002', 221);
INSERT INTO glacier_hazard.event2damage_type(fk_event, fk_damage_type) VALUES ('b26b3dea-a237-11ed-a8fc-0242ac120002', 300);


-- event3hazard_type
INSERT INTO glacier_hazard.event2hazard_type(fk_event, fk_hazard_type) VALUES ('b26b373c-a237-11ed-a8fc-0242ac120002',32);
INSERT INTO glacier_hazard.event2hazard_type(fk_event, fk_hazard_type) VALUES ('b26b3aa2-a237-11ed-a8fc-0242ac120002',32);
INSERT INTO glacier_hazard.event2hazard_type(fk_event, fk_hazard_type) VALUES ('b26b3c50-a237-11ed-a8fc-0242ac120002',21);
INSERT INTO glacier_hazard.event2hazard_type(fk_event, fk_hazard_type) VALUES ('b26b3dea-a237-11ed-a8fc-0242ac120002',22);

-- event2geometries